language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "4"
  - "5"
  - "iojs-v2"
sudo: false

before_install:
  - openssl aes-256-cbc -K $encrypted_6029cfe078d1_key -iv $encrypted_6029cfe078d1_iv -in birdknife.json.enc -out lib/test/config.json -d
