language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "4"
  - "5"
  - "iojs-v2"
sudo: false

before_install:
  - mkdir -p node_modules/gulp/bin/
  - openssl aes-256-cbc -K $encrypted_9bb834128f14_key -iv $encrypted_9bb834128f14_iv -in config_travis.json.enc -out test/config.json -d
